import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const output = new URL('../out/', import.meta.url);
async function files(dir, prefix = '') {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(entries.map(entry => entry.isDirectory() ? files(join(dir, entry.name), `${prefix}${entry.name}/`) : `${prefix}${entry.name}`));
  return nested.flat();
}
const list = (await files(fileURLToPath(output))).filter(name => /\.(js|css|woff2|png|svg|webmanifest)$/.test(name) && name !== 'sw.js').sort();
// Include file contents: public icons and the manifest keep their names between builds.
const digest = createHash('sha256').update(await readFile(new URL('index.html', output)));
for (const name of list) digest.update(name).update(await readFile(new URL(name, output)));
const hash = digest.digest('hex').slice(0,12);
const precache = ['/', ...list.map(name => '/' + name)];
const worker = `/* Generated by scripts/build-offline.mjs. Only this application's public assets are cached. */
const CACHE = 'spotjobs-worker-${hash}';
const ASSETS = ${JSON.stringify(precache)};
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS))); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => (key.startsWith('spotjobs-worker-') || key.startsWith('spotlog-')) && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).then(async response => { if (response.ok && url.pathname === '/') { const cache = await caches.open(CACHE); await cache.put('/', response.clone()); } return response; }).catch(async () => (await (await caches.open(CACHE)).match('/')) || Response.error()));
  } else if (ASSETS.includes(url.pathname) || url.pathname.startsWith('/_next/static/')) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(url.pathname);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) await cache.put(url.pathname, response.clone());
      return response;
    })());
  }
});
`;
await writeFile(new URL('sw.js', output), worker, 'utf8');
console.log(`Offline shell ready: ${precache.length} assets, ${hash}`);
